#!/bin/sh

# Подстановка переменных окружения в конфигурационный файл
envsubst '$DOMAIN' < /etc/nginx/myTemplates/${APP_ENV}.conf.template > /etc/nginx/sites-enabled/main.site.autogenerated.conf

# Запуск Nginx в форграунд режиме
nginx -g 'daemon off;'
